config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    resources :notes
  end
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
end

app/models/note.rb
class Note < ApplicationRecord
  
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 60 }
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  before_action :set_user
  before_action :set_note, only: [:show, :update, :edit, :destroy]
  before_action :logged_in_user
  before_action :correct_user
  
  def index
    @notes = @user.notes.all
  end
  
  def show
    @note = @user.notes.find(params[:id])
  end
  
  def new
    @note = Note.new
  end
  
  def create
    @note = @user.notes.create(note_params)
    if @note.save
      flash[:success] = "Note created!"
      redirect_to user_notes_url
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @note.update(note_params)
      flash[:success] = "Note updated!"
      redirect_to user_note_url
    else
      render 'edit'
    end
  end
  
  def destroy
    if @note.destroy
      flash[:success] = "Note deleted!"
    else
      flash[:danger]  = "Error deleting note!"
    end
    redirect_to user_notes_url
  end
  
  
  private
    
    def set_user
      @user = User.find_by_id(params[:user_id])
    end
    
    def set_note
      @note = @user.notes.find(params[:id])
    end
    
    def note_params
      params.require(:note).permit(:title, :content)
    end
    
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_edit_form.html.erb
<%= form_for([@user, @note], url: user_note_path(@user, @note)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "Note title...", class: "form-control" %>
  
  <%= f.label :content %>
  <%= f.text_area :content, placeholder: "The content of your note...", class: "form-control edit-text" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <br />
  <%= link_to "Cancel", user_note_path, class: "cancel btn btn-danger" %>
<% end %>

app/views/notes/_new_form.html.erb
<%= form_for([@user, @note], url: user_notes_path(@user, @note)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "Note title...", class: "form-control" %>
  
  <%= f.label :content %>
  <%= f.text_area :content, placeholder: "The content of your note...", class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <br />
  <%= link_to "Cancel", user_notes_path, class: "cancel btn btn-danger" %>
<% end %>

app/views/notes/edit.html.erb
<%= provide(:title, 'Edit Note') %>
<%= provide(:button_text, 'Edit Note') %>

<div class="container">
  <div class="row">
    <div class="forms col-md-6 offset-md-3">
      <h1 class="text-center">Edit Note</h1>
      
      <%= render 'edit_form' %>
      <br />
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<%= provide(:title, "All Notes") %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center">All Notes</h1>
      <br />
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="card-columns">
        <% @user.notes.each do |note| %>
          <div class="card text-center">
            <img class="card-img-top" <%= image_tag('card.png', class: "img-thumbnail") %>
            <div class="card-body">
              <h5 class="card-title"><%= note.title %></h5><br />
              <a class="btn btn-primary" <%= link_to('View Note', user_note_path(@user, note)) %></a><br /><br />
              <p class="card-text"><small class="text-muted">Created: <%= time_ago_in_words(note.created_at) %> ago<br />
                Updated: <%= time_ago_in_words(note.updated_at) %> ago</small></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<%= provide(:title, "New Note") %>
<%= provide(:button_text, "Create Note") %>

<div class="container">
  <div class="row">
    <div class="forms col-md-6 offset-md-3">
      <h1 class="text-center">New Note</h1>
      
      <%= render 'new_form' %>
      <br />
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<%= provide(:title, @note.title) %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center"><%= @note.title %></h1>
      
      <br />
      <p><%= simple_format(@note.content) %></p>
      
      
      <br /><br /><br />
      <h4 class="text-center"><%= link_to "Edit Note", edit_user_note_path(@user, @note) %> | <%= link_to "Delete", user_note_path(@user, @note), method: :delete, data: { confirm: "Are you sure? This action cannot be undone." } %> | <%= link_to "All Notes", user_notes_path %></h4>
    </div>
  </div>
</div>