config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    resources :notes
  end
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand">
    <%= link_to root_path do %>
      <%= image_tag("logo.png", class: "img-responsive d-inline-block align-top", id: "navbar_logo") %>
    <% end %>
  </a>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="nav navbar-nav ml-auto">
      
      <!-- Logged in -->
      <% if logged_in? %>
      <li class="nav-item">
        <a class="nav-link" <%= link_to new_user_note_path(@user, @note) do %>
          <i class="fa fa-plus"></i>
        <% end %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"
          <%= link_to('Notes', user_notes_path(@user)) %>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link"<%= link_to "Log out", logout_path, method: :delete %></a>
      </li>
        
      <!-- Logged out -->
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/signup">Sign up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/login">Log in</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Notes App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>